// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using petgoods4all.Models;

namespace petgoods4all.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20181030160623_Initialpetgoods4allDB")]
    partial class Initialpetgoods4allDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("petgoods4all.Models.Account", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Admin");

                    b.Property<string>("achternaam");

                    b.Property<string>("email");

                    b.Property<string>("password");

                    b.Property<string>("straatnaam");

                    b.Property<string>("telefoonnummer");

                    b.Property<string>("voornaam");

                    b.HasKey("id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("petgoods4all.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountId");

                    b.Property<DateTime>("Datum");

                    b.Property<string>("OrderStatus");

                    b.Property<string>("Prijs");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("petgoods4all.Models.OrderedProducts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("OrderId");

                    b.Property<int>("ProductId");

                    b.Property<int>("Quantity");

                    b.HasKey("Id");

                    b.ToTable("OrderedProducts");
                });

            modelBuilder.Entity("petgoods4all.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountId");

                    b.Property<int>("Quantity");

                    b.Property<int>("VoorraadId");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCart");
                });

            modelBuilder.Entity("petgoods4all.Models.Voorraad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Dier");

                    b.Property<int>("Kwantiteit");

                    b.Property<string>("Naam");

                    b.Property<string>("Prijs");

                    b.Property<string>("Subklasse");

                    b.Property<string>("image");

                    b.HasKey("Id");

                    b.ToTable("Voorraad");
                });

            modelBuilder.Entity("petgoods4all.Models.Wishlist", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("customerid");

                    b.Property<int>("productid");

                    b.HasKey("id");

                    b.ToTable("Wishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
